export enum OrderStatus {
  RECEIVED = 'Received',
  PROCESSING = 'Processing',
  SHIPPED = 'Shipped',
  OUT_FOR_DELIVERY = 'Out for delivery',
  CANCELED = 'Canceled',
  SENT_TO_LOCAL_PHARMACY = 'SENT_TO_LOCAL_PHARMACY',
  SENT_TO_HALLANDALE = 'SENT_TO_HALLANDALE',
  SENT_TO_RED_ROCK = 'SENT_TO_RED_ROCK',
  BUNDLED_REFILL_2 = 'BUNDLED_REFILL_2',
  BUNDLED_REFILL_3 = 'BUNDLED_REFILL_3',
  ORDER_PENDING_ACTION = 'ACTION_PENDING',
  PAYMENT_SUCCESS = 'Paid and pending shipping',
  SENT_TO_GOGOMEDS = 'Shipment in progress',
  ORDER_CREATED = 'In Progress',
  IN_SHIPPING = 'In Shipping',
  'Order Canceled' = 'Order Canceled',
  PAYMENT_FAILED = 'Payment unsuccessful',
  DELIVERED = 'Delivered',
  COMPLETE = 'Complete',
}
