export const AMH_Medication_Dosages = {
  Abilify: [
    { text: '10 mg', code: 'ASYNC_MH_CMT_Q1_A1' },
    { text: '20 mg', code: 'ASYNC_MH_CMT_Q1_A2' },
    { text: '40 mg', code: 'ASYNC_MH_CMT_Q1_A3' },
    { text: 'Something else', code: 'ASYNC_MH_CMT_Q1_A4' },
    { text: `I'm not sure`, code: 'ASYNC_MH_CMT_Q1_A5' },
  ],
  Adderall: [
    { text: '10 mg', code: 'ASYNC_MH_CMT_Q1_A6' },
    { text: '20 mg', code: 'ASYNC_MH_CMT_Q1_A7' },
    { text: '40 mg', code: 'ASYNC_MH_CMT_Q1_A8' },
    { text: 'Something else', code: 'ASYNC_MH_CMT_Q1_A9' },
    { text: `I'm not sure`, code: 'ASYNC_MH_CMT_Q1_A10' },
  ],
  Celexa: [
    { text: '10 mg', code: 'ASYNC_MH_CMT_Q1_A11' },
    { text: '20 mg', code: 'ASYNC_MH_CMT_Q1_A12' },
    { text: '40 mg', code: 'ASYNC_MH_CMT_Q1_A13' },
    { text: 'Something else', code: 'ASYNC_MH_CMT_Q1_A14' },
    { text: `I'm not sure`, code: 'ASYNC_MH_CMT_Q1_A15' },
  ],
  Fluoxetine: [
    { text: '10 mg', code: 'ASYNC_MH_CMT_Q1_A16' },
    { text: '20 mg', code: 'ASYNC_MH_CMT_Q1_A17' },
    { text: '30 mg', code: 'ASYNC_MH_CMT_Q1_A18' },
    { text: '40 mg', code: 'ASYNC_MH_CMT_Q1_A19' },
    { text: '60 mg', code: 'ASYNC_MH_CMT_Q1_A20' },
    { text: '80 mg', code: 'ASYNC_MH_CMT_Q1_A21' },
    { text: 'Something else', code: 'ASYNC_MH_CMT_Q1_A22' },
    { text: `I'm not sure`, code: 'ASYNC_MH_CMT_Q1_A23' },
  ],
  Escitalopram: [
    { text: '5 mg', code: 'ASYNC_MH_CMT_Q1_A24' },
    { text: '10 mg', code: 'ASYNC_MH_CMT_Q1_A25' },
    { text: '15 mg', code: 'ASYNC_MH_CMT_Q1_A26' },
    { text: '20 mg', code: 'ASYNC_MH_CMT_Q1_A27' },
    { text: 'Something else', code: 'ASYNC_MH_CMT_Q1_A28' },
    { text: `I'm not sure`, code: 'ASYNC_MH_CMT_Q1_A29' },
  ],
  Wellbutrin: [
    { text: '100 mg', code: 'ASYNC_MH_CMT_Q1_A30' },
    { text: '150 mg', code: 'ASYNC_MH_CMT_Q1_A31' },
    { text: '300 mg', code: 'ASYNC_MH_CMT_Q1_A32' },
    { text: '450 mg', code: 'ASYNC_MH_CMT_Q1_A33' },
    { text: 'Something else', code: 'ASYNC_MH_CMT_Q1_A34' },
    { text: `I'm not sure`, code: 'ASYNC_MH_CMT_Q1_A35' },
  ],
  Sertraline: [
    { text: '25 mg', code: 'ASYNC_MH_CMT_Q1_A36' },
    { text: '50 mg', code: 'ASYNC_MH_CMT_Q1_A37' },
    { text: '75 mg', code: 'ASYNC_MH_CMT_Q1_A38' },
    { text: '100 mg', code: 'ASYNC_MH_CMT_Q1_A39' },
    { text: '125 mg', code: 'ASYNC_MH_CMT_Q1_A40' },
    { text: '150 mg', code: 'ASYNC_MH_CMT_Q1_A41' },
    { text: '200 mg', code: 'ASYNC_MH_CMT_Q1_A42' },
    { text: 'Something else', code: 'ASYNC_MH_CMT_Q1_A43' },
    { text: `I'm not sure`, code: 'ASYNC_MH_CMT_Q1_A44' },
  ],
  Buspar: [
    { text: '10 mg (5 mg twice daily)', code: 'ASYNC_MH_CMT_Q1_A45' },
    { text: '15 mg (7.5 mg twice daily)', code: 'ASYNC_MH_CMT_Q1_A46' },
    { text: '20 mg (10 mg twice daily)', code: 'ASYNC_MH_CMT_Q1_A47' },
    { text: '30 mg (15 mg twice daily)', code: 'ASYNC_MH_CMT_Q1_A48' },
    { text: '40 mg (20 mg twice daily)', code: 'ASYNC_MH_CMT_Q1_A49' },
    { text: 'Something else', code: 'ASYNC_MH_CMT_Q1_A50' },
    { text: `I'm not sure`, code: 'ASYNC_MH_CMT_Q1_A51' },
  ],
} as const;
